server:
  port: 8091
spring:
  application:
    name: demo-service
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/